// Generated by https://quicktype.io

export interface MovieSearch {
    page:          number;
    results:       Media[];
    total_pages:   number;
    total_results: number;
}

export interface Media {
    adult:             boolean;
    backdrop_path:     string;
    id:                number;
    title:             string;
    original_language: string;
    original_title:    string;
    overview:          string;
    poster_path:       string;
    media_type:        string;
    genre_ids:         number[];
    popularity:        number;
    release_date:      string;
    video:             boolean;
    vote_average:      number;
    vote_count:        number;
}



export interface PersonSearch {
    page:          number;
    results:       Person[];
    total_pages:   number;
    total_results: number;
}

export interface Person {
    adult:                boolean;
    gender:               number;
    id:                   number;
    known_for_department: string;
    name:                 string;
    original_name:        string;
    popularity:           number;
    profile_path:         string;
    known_for:            Media[];
}





// Generated by https://quicktype.io

export interface MovieCredits {
    cast: Cast[];
    crew: Cast[];
    id:   number;
}

export interface Cast {
    adult:             boolean;
    backdrop_path:     null | string;
    genre_ids:         number[];
    id:                number;
    original_language: OriginalLanguage;
    original_title:    string;
    overview:          string;
    popularity:        number;
    poster_path:       null | string;
    release_date:      string;
    title:             string;
    video:             boolean;
    vote_average:      number;
    vote_count:        number;
    character?:        string;
    credit_id:         string;
    order?:            number;
    department?:       string;
    job?:              string;
}

export enum OriginalLanguage {
    En = "en",
    Es = "es",
}
